server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: yinyang-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values:
              - yinyang-api-1
              - yinyang-worker-1
              - yinyang-beat-1
              - yinyang-frontend-1
    relabel_configs:
      # lấy tên container làm label
      - source_labels: [__meta_docker_container_name]
        regex: /(.*)
        target_label: container
      # lấy image làm label
      - source_labels: [__meta_docker_container_image_name]
        target_label: image
      # thêm label app cố định
      - target_label: app
        replacement: yinyang
