
export const styles = {
  pageContainer: {
    minHeight: "100vh",
    fontFamily: "Arial, sans-serif",
    backgroundColor: "#FDF9F1",
    margin: 0,
    padding: 0,
    overflowX: "hidden",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "15px 30px",
    backgroundColor: "#051A30",
    color: "white",
    flexWrap: "wrap",
    gap: "15px",
    position: "relative",
    zIndex: 100,
  },
  logo: {
    fontSize: "24px",
    fontWeight: "bold",
    letterSpacing: "2px",
    cursor: "pointer",
  },
  navMenu: {
    display: "flex",
    gap: "25px",
    alignItems: "center",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  navLink: {
    fontSize: "13px",
    fontWeight: "600",
    color: "#D0D9E0",
    cursor: "pointer",
    letterSpacing: "0.5px",
    transition: "0.3s",
  },
  authSection: {
    position: "relative",
  },
  col: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  loginButton: {
    backgroundColor: "transparent",
    color: "white",
    border: "1px solid white",
    padding: "8px 20px",
    borderRadius: "20px",
    cursor: "pointer",
    fontWeight: "bold",
    whiteSpace: "nowrap",
  },
  userProfile: {
    position: "relative",
    display: "inline-block",
  },
  avatarWrapper: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    cursor: "pointer",
    padding: "5px 15px 5px 5px",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: "25px",
    border: "1px solid rgba(255, 255, 255, 0.2)",
  },
  avatarImage: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    objectFit: "cover",
  },
  userName: {
    fontSize: "14px",
    fontWeight: "bold",
    color: "white",
  },
  arrowDown: {
    fontSize: "10px",
    color: "#D0D9E0",
  },
  dropdownMenu: {
    position: "absolute",
    top: "130%",
    right: "0",
    backgroundColor: "white",
    borderRadius: "10px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.15)",
    width: "200px",
    overflow: "hidden",
    zIndex: 999,
  },
  dropdownItem: {
    padding: "15px 20px",
    fontSize: "14px",
    color: "#333",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  dropdownDivider: {
    height: "1px",
    backgroundColor: "#eee",
    margin: "0",
  },
  yinyangSection: {
    background: "linear-gradient(180deg, #051A30 0%, #295985 100%)",
    padding: "40px 20px 60px 20px",
    textAlign: "center",
    color: "white",
  },
  mainTitle: {
    fontSize: "32px",
    margin: "0 0 10px 0",
    textTransform: "uppercase",
  },
  subTitle: {
    fontSize: "14px",
    marginBottom: "30px",
    lineHeight: "1.5",
    opacity: 0.9,
  },
  formCard: {
    backgroundColor: "white",
    borderRadius: "15px",
    padding: "20px",
    maxWidth: "400px",
    margin: "0 auto",
    boxShadow: "0 10px 25px rgba(0,0,0,0.1)",
  },
  inputFull: {
    width: "100%",
    padding: "12px",
    marginBottom: "15px",
    border: "1px solid #ccc",
    borderRadius: "8px",
    boxSizing: "border-box",
  },
  row: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "15px",
    gap: "10px",
  },
  inputHalf: {
    width: "48%",
    padding: "12px",
    border: "1px solid #ccc",
    borderRadius: "8px",
    boxSizing: "border-box",
  },
  submitButton: {
    width: "100%",
    padding: "15px",
    backgroundColor: "#051A30",
    color: "white",
    fontWeight: "bold",
    fontSize: "16px",
    border: "none",
    borderRadius: "25px",
    cursor: "pointer",
    marginTop: "10px",
  },
  linkText: {
    color: "#3879b5ff",
    fontSize: "13px",
    marginTop: "15px",
    textDecoration: "underline",
    cursor: "pointer",
    textAlign: "center",
  },
  featuresSection: {
    padding: "40px 20px 60px 20px",
    textAlign: "center",
  },
  featureGrid: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: "15px",
    maxWidth: "500px",
    margin: "0 auto",
  },
  featureItem: {
    backgroundColor: "white",
    padding: "15px 20px",
    borderRadius: "10px",
    boxShadow: "0 4px 6px rgba(0,0,0,0.05)",
    width: "40%",
    fontWeight: "bold",
    color: "#333",
  },
  zodiacSection: {
    width: "100%",
    margin: "0 auto",
    padding: 30,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: "#d4bfef",
  },
  zodiacImage: {
    width: "100%",
    height: "auto",
    objectFit: "cover",
    display: "block",
  },
  zodiacButton: {
    width: "20%",
    padding: "15px",
    backgroundColor: "#051A30",
    color: "white",
    fontWeight: "bold",
    fontSize: "16px",
    border: "none",
    borderRadius: "25px",
    cursor: "pointer",
    marginTop: "10px",
  },
  footer: {
    backgroundColor: "#051A30",
    color: "white",
    padding: "50px 30px 20px 30px",
    fontSize: "14px",
    marginTop: 0,
  },
  footerTop: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    maxWidth: "1200px",
    margin: "0 auto",
    gap: "30px",
  },
  footerColInfo: {
    flex: "2 1 250px",
  },
  footerIntro: {
    lineHeight: "1.6",
    color: "#D0D9E0",
    marginBottom: "20px",
  },
  socialIcons: {
    display: "flex",
    gap: "10px",
    marginBottom: "15px",
  },
  iconCircle: {
    width: "35px",
    height: "35px",
    borderRadius: "50%",
    backgroundColor: "#295985",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontWeight: "bold",
  },
  footerEmail: {
    color: "white",
    textDecoration: "underline",
    cursor: "pointer",
  },
  footerCol: {
    flex: "1 1 120px",
  },
  footerColTitle: {
    color: "#D0D9E0",
    fontSize: "13px",
    marginBottom: "20px",
    textTransform: "uppercase",
  },
  footerLink: {
    color: "#D0D9E0",
    marginBottom: "15px",
    cursor: "pointer",
  },
  footerColNewsletter: {
    flex: "1 1 250px",
  },
  newsletterInputContainer: {
    display: "flex",
    backgroundColor: "white",
    borderRadius: "5px",
    overflow: "hidden",
    marginTop: "10px",
  },
  newsletterInput: {
    flex: 1,
    padding: "12px 15px",
    border: "none",
    outline: "none",
    fontSize: "14px",
  },
  newsletterBtn: {
    backgroundColor: "white",
    border: "none",
    padding: "0 15px",
    cursor: "pointer",
    fontSize: "18px",
    color: "#051A30",
  },
  footerDivider: {
    height: "1px",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    margin: "40px auto 30px auto",
    maxWidth: "1200px",
  },
  footerBottom: {
    textAlign: "center",
  },
  footerLogoBottom: {
    fontSize: "28px",
    fontWeight: "bold",
    letterSpacing: "3px",
    margin: 0,
  },
};