"""init

Revision ID: 5ee7f6aca042
Revises: 
Create Date: 2026-03-31 02:11:10.729166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ee7f6aca042'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('facebook_id', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('nguoi_dung', 'nghien_cuu', 'chuyen_gia', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('streak_count', sa.Integer(), nullable=False),
    sa.Column('notify_channel', sa.Enum('email', 'push', 'both', name='notify_channel'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('facebook_id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chart_configurations',
    sa.Column('configuration_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('configuration_id')
    )
    op.create_index(op.f('ix_chart_configurations_user_id'), 'chart_configurations', ['user_id'], unique=False)
    op.create_table('clients',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('expert_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('last_consultation', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expert_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_clients_expert_id'), 'clients', ['expert_id'], unique=False)
    op.create_table('journal_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('luu_sao_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_journal_logs_log_date'), 'journal_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_journal_logs_user_id'), 'journal_logs', ['user_id'], unique=False)
    op.create_table('appointments',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('expert_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', name='appointment_status'), nullable=False),
    sa.Column('payment_status', sa.Enum('unpaid', 'paid', 'refunded', name='payment_status'), nullable=False),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expert_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_index(op.f('ix_appointments_client_id'), 'appointments', ['client_id'], unique=False)
    op.create_index(op.f('ix_appointments_expert_id'), 'appointments', ['expert_id'], unique=False)
    op.create_table('charts',
    sa.Column('chart_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('dob_solar_enc', sa.Text(), nullable=False),
    sa.Column('birth_hour_enc', sa.Text(), nullable=False),
    sa.Column('dob_lunar_year', sa.Integer(), nullable=True),
    sa.Column('dob_lunar_month', sa.Integer(), nullable=True),
    sa.Column('dob_lunar_day', sa.Integer(), nullable=True),
    sa.Column('dob_lunar_leap', sa.Boolean(), nullable=False),
    sa.Column('chart_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('configuration_id', sa.UUID(), nullable=True),
    sa.Column('ai_interpretation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_cached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['chart_configurations.configuration_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chart_id')
    )
    op.create_index(op.f('ix_charts_user_id'), 'charts', ['user_id'], unique=False)
    op.create_table('annotations',
    sa.Column('annotation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chart_id', sa.UUID(), nullable=False),
    sa.Column('house_number', sa.Integer(), nullable=True),
    sa.Column('star_name', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.chart_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('annotation_id')
    )
    op.create_index(op.f('ix_annotations_chart_id'), 'annotations', ['chart_id'], unique=False)
    op.create_index(op.f('ix_annotations_user_id'), 'annotations', ['user_id'], unique=False)
    op.create_table('attachments',
    sa.Column('attachment_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.appointment_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_index(op.f('ix_attachments_client_id'), 'attachments', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_client_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_annotations_user_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_chart_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_charts_user_id'), table_name='charts')
    op.drop_table('charts')
    op.drop_index(op.f('ix_appointments_expert_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_client_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_journal_logs_user_id'), table_name='journal_logs')
    op.drop_index(op.f('ix_journal_logs_log_date'), table_name='journal_logs')
    op.drop_table('journal_logs')
    op.drop_index(op.f('ix_clients_expert_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_chart_configurations_user_id'), table_name='chart_configurations')
    op.drop_table('chart_configurations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
